import Head from 'next/head';
import CommitmentSection from '../components/sections/commitment/commitment';
import HeroSection from '../components/sections/hero/hero';


export async function getStaticProps(){
  const data = await import('../public/commitments/data.json'); 

  return {
    props: { commitments: data.commitments }
  }  
}



export default function Home({ commitments }) {
  

  return (
    <>
      <Head>
        <title>Tech People</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" type="image/png" href="/ico.png" />
      </Head>     
      <HeroSection/>
      <CommitmentSection data={ commitments }/>
    </>
  )
}
